apiVersion: apps/v1
kind: Deployment
metadata:
  name: urca-tournament
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: urca-tournament
          imagePullPolicy: IfNotPresent
