apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - http-route.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: urca-tournament
      spec:
        replicas: 2
    target:
      kind: Deployment

images:
  - name: ghcr.io/REPLACE_WITH_USERNAME/urca-tournament
    newTag: latest
