apiVersion: v1
kind: Secret
metadata:
  name: urca-tournament-secret
type: Opaque
stringData:
  JWT_SECRET: "change-me-in-production"
  MONGO_PASSWORD: "change-me-in-production"
  DB_CONNECTION_STRING: "mongodb://root:change-me-in-production@mongodb:27017/tournament?authSource=admin"
